// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdVuSlrxtUULBlsIWJgbSSXY4fqFTsuwI',
    appId: '1:584839649705:web:678b61f12c97a590ab8cb8',
    messagingSenderId: '584839649705',
    projectId: 'flutter-chatting-79ad1',
    authDomain: 'flutter-chatting-79ad1.firebaseapp.com',
    storageBucket: 'flutter-chatting-79ad1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcn42BIFU3lDbiLPYbYJj_6bF157LcOK4',
    appId: '1:584839649705:android:9d625f7e3d6480d9ab8cb8',
    messagingSenderId: '584839649705',
    projectId: 'flutter-chatting-79ad1',
    storageBucket: 'flutter-chatting-79ad1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTXo5F4mwLBAQ-UvZOXGaZQcaVgQDoyB0',
    appId: '1:584839649705:ios:225716bc28beeee6ab8cb8',
    messagingSenderId: '584839649705',
    projectId: 'flutter-chatting-79ad1',
    storageBucket: 'flutter-chatting-79ad1.appspot.com',
    iosBundleId: 'com.juhnkim.java22MobiltJuhnKimSlutprojektSprintV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTXo5F4mwLBAQ-UvZOXGaZQcaVgQDoyB0',
    appId: '1:584839649705:ios:4026d68581c9f29aab8cb8',
    messagingSenderId: '584839649705',
    projectId: 'flutter-chatting-79ad1',
    storageBucket: 'flutter-chatting-79ad1.appspot.com',
    iosBundleId: 'com.juhnkim.java22MobiltJuhnKimSlutprojektSprintV3.RunnerTests',
  );
}
